//
//  SymbolData.swift
//  Walkie Talkie AAC
//
//  Auto-generated. Do not edit.
//

import Foundation

extension SymbolLibrary {

    static let embeddedWordMap: [String: String] = [
        "above": "above",
        "absent": "absent",
        "across": "across",
        "add": "number_add",
        "advent": "advent",
        "aeroplane": "aeroplane",
        "after": "after",
        "afternoon": "afternoon",
        "against": "against",
        "ahead": "ahead",
        "almond": "almond",
        "ambulance": "ambulance",
        "angel": "angel",
        "answer": "answer",
        "ant": "ant",
        "arm": "arm",
        "armwrestle": "armwrestle",
        "around": "around",
        "art": "art",
        "ask": "ask",
        "assembly": "assembly",
        "assistance": "assistance",
        "atom": "atom",
        "autumn": "autumn",
        "awake": "awake",
        "away": "away",
        "baby": "baby",
        "backwards": "backwards",
        "bad": "bad",
        "badminton": "badminton",
        "bagel": "bagel",
        "bake": "bake",
        "ball": "ball",
        "bank": "bank",
        "bap": "bap",
        "basketball": "basketball",
        "bat": "bat",
        "bath": "bath",
        "bathe": "bathe",
        "beach": "beach",
        "beak": "beak",
        "bed": "bed",
        "beef": "beef",
        "beer": "beer",
        "before": "before",
        "behind": "behind",
        "bell": "bell",
        "below": "below",
        "bench": "bench",
        "bendy": "bendy",
        "between": "between",
        "bib": "bib",
        "bingo": "bingo",
        "bird": "bird",
        "black": "black",
        "blackboard": "blackboard",
        "bless": "bless",
        "blue": "blue",
        "boat": "boat",
        "bolt": "bolt",
        "bone": "bone",
        "bonfire": "bonfire",
        "both": "both",
        "bottom": "bottom",
        "bow": "bow",
        "bowl": "bowl",
        "box": "box",
        "bra": "bra",
        "brazil": "brazil",
        "break": "break",
        "bridle": "bridle",
        "bright": "bright",
        "broken": "broken",
        "brooch": "brooch",
        "buckle": "buckle",
        "bud": "bud",
        "bumpy": "bumpy",
        "burn": "burn",
        "bus": "bus",
        "bush": "bush",
        "busy": "busy",
        "butter": "butter",
        "cafe": "cafe",
        "cage": "cage",
        "cake": "cake",
        "calendar": "calendar",
        "call": "call",
        "camera": "camera",
        "canada": "canada",
        "canoe": "canoe",
        "cap": "cap",
        "car": "car",
        "carbohydrates": "carbohydrates",
        "card": "card",
        "cart": "cart",
        "cashew": "cashew",
        "castle": "castle",
        "cat": "cat",
        "cctv": "cctv",
        "celebration": "celebration",
        "chair": "chair",
        "chalk": "chalk",
        "cheese": "cheese",
        "chicken": "chicken",
        "china": "china",
        "chips": "chips",
        "chop": "chop",
        "church": "church",
        "cigarette": "cigarette",
        "circle": "circle",
        "claw": "claw",
        "clay": "clay",
        "clipboard": "clipboard",
        "clock": "clock",
        "closed": "closed",
        "cloudy": "cloudy",
        "coffee": "coffee",
        "cold": "cold",
        "comb": "comb",
        "comet": "comet",
        "cook": "cook",
        "copy": "copy",
        "correct": "correct",
        "cot": "cot",
        "counters": "counters",
        "cow": "cow",
        "crab": "crab",
        "cream": "cream",
        "cricket": "cricket",
        "crooked": "crooked",
        "cross": "cross",
        "cruiser": "cruiser",
        "curly": "curly",
        "curry": "curry",
        "cut": "cut",
        "darts": "darts",
        "date": "date",
        "day": "day",
        "dead": "dead",
        "deep": "deep",
        "desk": "desk",
        "diamond": "diamond",
        "die": "die",
        "dirty": "dirty",
        "disability": "disability",
        "disabled": "disabled",
        "dishwasher": "dishwasher",
        "divide": "divide",
        "doctor": "doctor",
        "dog": "dog",
        "doll": "doll",
        "dolphin": "dolphin",
        "door": "door",
        "dove": "dove",
        "down": "down",
        "drama": "drama",
        "drink": "drink",
        "drinks": "drinks",
        "drum": "drum",
        "dry": "dry",
        "duck": "duck",
        "dust": "dust",
        "ear": "ear",
        "earrings": "earrings",
        "earthworm": "earthworm",
        "east": "east",
        "egg": "egg",
        "eggs": "eggs",
        "egypt": "egypt",
        "eighth": "eighth",
        "either": "either",
        "elearning": "elearning",
        "elf": "elf",
        "email": "email",
        "empty": "empty",
        "england": "england",
        "enough": "enough",
        "enter": "enter",
        "even": "even",
        "every": "every",
        "exit": "exit",
        "extra": "extra",
        "eye": "eye",
        "family": "family",
        "fancy": "fancy",
        "fat": "fat",
        "fats": "fats",
        "favourite": "favourite",
        "ferry": "ferry",
        "field": "field",
        "fig": "fig",
        "file": "file",
        "fin": "fin",
        "finish": "finish",
        "fire": "fire",
        "first": "first",
        "fish": "fish",
        "flame": "flame",
        "flat": "flat",
        "floor": "floor",
        "flute": "flute",
        "fly": "fly",
        "food": "food",
        "football": "football",
        "forward": "forward",
        "forwards": "forwards",
        "france": "france",
        "frog": "frog",
        "fry": "fry",
        "full": "full",
        "future": "future",
        "fuzzy": "fuzzy",
        "garage": "garage",
        "germany": "germany",
        "glass": "glass",
        "globe": "globe",
        "glue": "glue",
        "gnat": "gnat",
        "go": "go",
        "goal": "goal",
        "golf": "golf",
        "good": "good",
        "great": "great",
        "greece": "greece",
        "guitar": "guitar",
        "gum": "gum",
        "guy": "guy",
        "half": "half",
        "halloween": "halloween",
        "ham": "ham",
        "hangar": "hangar",
        "happy": "happy",
        "hard": "hard",
        "headache": "headache",
        "headmouse": "headmouse",
        "heavy": "heavy",
        "helicopter": "helicopter",
        "hello": "hello",
        "helmet": "helmet",
        "help": "help",
        "heptagon": "heptagon",
        "hexagon": "hexagon",
        "high": "high",
        "highest": "highest",
        "hoe": "hoe",
        "hoist": "hoist",
        "holdall": "holdall",
        "hollow": "hollow",
        "home": "home",
        "honey": "honey",
        "hoover": "hoover",
        "hose": "hose",
        "hot": "hot",
        "house": "house",
        "how": "how",
        "hungry": "hungry",
        "in": "in",
        "inbox": "inbox",
        "india": "india",
        "intellikeys": "intellikeys",
        "iphone": "iphone",
        "ipod": "ipod",
        "ireland": "ireland",
        "iron": "iron",
        "italy": "italy",
        "itch": "itch",
        "ivy": "ivy",
        "jam": "jam",
        "jamaica": "jamaica",
        "japan": "japan",
        "jar": "jar",
        "jeep": "jeep",
        "jelly": "jelly",
        "jellyfish": "jellyfish",
        "jesus": "jesus",
        "judas": "judas",
        "judo": "judo",
        "kennel": "kennel",
        "kite": "kite",
        "kiwi": "kiwi",
        "lamb": "lamb",
        "lamp": "lamp",
        "laptop": "laptop",
        "large": "large",
        "last": "last",
        "lead": "lead",
        "leek": "leek",
        "left": "left",
        "lens": "lens",
        "lent": "lent",
        "lid": "lid",
        "lift": "lift",
        "light": "light",
        "lime": "lime",
        "little": "little",
        "lizard": "lizard",
        "log": "log",
        "long": "long",
        "lost": "lost",
        "loud": "loud",
        "love": "love",
        "lowest": "lowest",
        "lucky": "lucky",
        "lump": "lump",
        "manger": "manger",
        "marmite": "marmite",
        "mars": "mars",
        "mary": "mary",
        "maths": "maths",
        "meat": "meat",
        "medal": "medal",
        "medicine": "medicine",
        "mend": "mend",
        "menu": "menu",
        "mexico": "mexico",
        "middle": "middle",
        "milk": "milk",
        "mints": "mints",
        "minute": "minute",
        "money": "money",
        "moon": "moon",
        "mop": "mop",
        "more": "more",
        "morning": "morning",
        "morocco": "morocco",
        "most": "most",
        "moth": "moth",
        "music": "music",
        "nail": "nail",
        "nappy": "nappy",
        "nativity": "nativity",
        "near": "near",
        "neither": "neither",
        "nest": "nest",
        "newspaper": "newspaper",
        "next": "next",
        "nigeria": "nigeria",
        "night": "night",
        "no": "no",
        "noisy": "noisy",
        "noodles": "noodles",
        "north": "north",
        "now": "now",
        "nurse": "nurse",
        "nuts": "nuts",
        "octagon": "octagon",
        "off": "off",
        "omelette": "omelette",
        "on": "on",
        "one": "one",
        "open": "open",
        "opposite": "opposite",
        "out": "out",
        "outside": "outside",
        "oval": "oval",
        "over": "over",
        "owl": "owl",
        "pakistan": "pakistan",
        "paper": "paper",
        "parachute": "parachute",
        "parallelogram": "parallelogram",
        "part": "part",
        "past": "past",
        "pasta": "pasta",
        "pate": "pate",
        "paw": "paw",
        "pe": "pe",
        "pea": "pea",
        "pear": "pear",
        "peas": "peas",
        "pecan": "pecan",
        "pen": "pen",
        "pentagon": "pentagon",
        "perm": "perm",
        "permeable": "permeable",
        "photocopier": "photocopier",
        "piano": "piano",
        "pie": "pie",
        "pink": "pink",
        "pint": "pint",
        "point": "point",
        "pointed": "pointed",
        "poland": "poland",
        "pond": "pond",
        "portugal": "portugal",
        "pot": "pot",
        "poultry": "poultry",
        "prawn": "prawn",
        "pray": "pray",
        "printer": "printer",
        "protein": "protein",
        "purse": "purse",
        "quadrilateral": "quadrilateral",
        "quarter": "quarter",
        "rain": "rain",
        "rainbow": "rainbow",
        "rake": "rake",
        "ramp": "ramp",
        "ravioli": "ravioli",
        "rectangle": "rectangle",
        "red": "red",
        "retire": "retire",
        "rhombus": "rhombus",
        "rice": "rice",
        "rifle": "rifle",
        "right": "right",
        "ring": "ring",
        "risen": "risen",
        "road": "road",
        "rocket": "rocket",
        "room": "room",
        "rosette": "rosette",
        "rug": "rug",
        "run": "run",
        "sack": "sack",
        "sad": "sad",
        "saddle": "saddle",
        "salad": "salad",
        "salty": "salty",
        "same": "same",
        "save": "save",
        "saw": "saw",
        "scared": "scared",
        "school": "school",
        "scotland": "scotland",
        "seal": "seal",
        "second": "second",
        "shallow": "shallow",
        "shapes": "shapes",
        "sharp": "sharp",
        "shave": "shave",
        "shells": "shells",
        "shiny": "shiny",
        "shop": "shop",
        "shrimp": "shrimp",
        "side": "side",
        "sister": "sister",
        "six": "six",
        "ski": "ski",
        "skis": "skis",
        "slice": "slice",
        "slide": "slide",
        "sling": "sling",
        "slowly": "slowly",
        "slug": "slug",
        "snail": "snail",
        "snake": "snake",
        "snow": "snow",
        "soap": "soap",
        "soft": "soft",
        "some": "some",
        "son": "son",
        "soup": "soup",
        "sour": "sour",
        "south": "south",
        "spaceship": "spaceship",
        "spain": "spain",
        "speak": "speak",
        "spicy": "spicy",
        "spotty": "spotty",
        "spring": "spring",
        "square": "square",
        "stable": "stable",
        "star": "star",
        "starfish": "starfish",
        "sticky": "sticky",
        "stock": "stock",
        "stool": "stool",
        "stop": "stop",
        "straight": "straight",
        "striped": "striped",
        "stroke": "stroke",
        "subsoil": "subsoil",
        "sum": "sum",
        "summer": "summer",
        "sun": "sun",
        "sweden": "sweden",
        "swing": "swing",
        "switzerland": "switzerland",
        "table": "table",
        "tall": "tall",
        "tap": "tap",
        "tart": "tart",
        "tea": "tea",
        "ten": "ten",
        "tennis": "tennis",
        "test": "test",
        "thanks": "thanks",
        "thick": "thick",
        "thin": "thin",
        "thirsty": "thirsty",
        "through": "through",
        "tie": "tie",
        "time": "time",
        "tin": "tin",
        "toad": "toad",
        "today": "today",
        "toilet": "toilet",
        "toilets": "toilets",
        "tomorrow": "tomorrow",
        "toothache": "toothache",
        "top": "top",
        "topsoil": "topsoil",
        "torch": "torch",
        "tracksuit": "tracksuit",
        "train": "train",
        "trap": "trap",
        "trapezium": "trapezium",
        "travel": "travel",
        "tuna": "tuna",
        "turkey": "turkey",
        "two": "two",
        "untie": "untie",
        "up": "up",
        "van": "van",
        "vinegar": "vinegar",
        "volleyball": "volleyball",
        "wales": "wales",
        "wall": "wall",
        "walrus": "walrus",
        "watch": "watch",
        "water": "water",
        "wavy": "wavy",
        "webcam": "webcam",
        "week": "week",
        "weekend": "weekend",
        "weigh": "weigh",
        "west": "west",
        "wet": "wet",
        "what": "what",
        "whiteboard": "whiteboard",
        "who": "who",
        "whole": "whole",
        "why": "why",
        "wife": "wife",
        "wii": "wii",
        "wine": "wine",
        "winter": "winter",
        "wishbone": "wishbone",
        "work": "work",
        "worksheet": "worksheet",
        "wrap": "wrap",
        "xray": "xray",
        "yes": "yes",
        "yesterday": "yesterday",
        "yogurt": "yogurt",
        "zip": "zip",
    ]

    static let embeddedSymbols: [CommunicationSymbol] = [
    CommunicationSymbol(id: "above", assetName: "above", displayLabel: "Above", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "absent", assetName: "absent", displayLabel: "Absent", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "across", assetName: "across", displayLabel: "Across", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "add", assetName: "number_add", displayLabel: "Add", category: "Communication", rawCategory: "Number Activity"),
    CommunicationSymbol(id: "advent", assetName: "advent", displayLabel: "Advent", category: "People & Places", rawCategory: "Religion Festival"),
    CommunicationSymbol(id: "aeroplane", assetName: "aeroplane", displayLabel: "Aeroplane", category: "Everyday Objects", rawCategory: "Transport Air"),
    CommunicationSymbol(id: "after", assetName: "after", displayLabel: "After", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "afternoon", assetName: "afternoon", displayLabel: "Afternoon", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "against", assetName: "against", displayLabel: "Against", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "ahead", assetName: "ahead", displayLabel: "Ahead", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "almond", assetName: "almond", displayLabel: "Almond", category: "Food & Drink", rawCategory: "Food Nuts"),
    CommunicationSymbol(id: "ambulance", assetName: "ambulance", displayLabel: "Ambulance", category: "Everyday Objects", rawCategory: "Transport Road"),
    CommunicationSymbol(id: "angel", assetName: "angel", displayLabel: "Angel", category: "People & Places", rawCategory: "Religion Person"),
    CommunicationSymbol(id: "answer", assetName: "answer", displayLabel: "Answer", category: "Communication", rawCategory: "Number Activity"),
    CommunicationSymbol(id: "ant", assetName: "ant", displayLabel: "Ant", category: "Animals & Nature", rawCategory: "Animal Spiders and Insects"),
    CommunicationSymbol(id: "arm", assetName: "arm", displayLabel: "Arm", category: "Body & Health", rawCategory: "Healthcare Body parts"),
    CommunicationSymbol(id: "armwrestle", assetName: "armwrestle", displayLabel: "Armwrestle", category: "Everyday Objects", rawCategory: "Leisure Games"),
    CommunicationSymbol(id: "around", assetName: "around", displayLabel: "Around", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "art", assetName: "art", displayLabel: "Art", category: "Everyday Objects", rawCategory: "Art Making"),
    CommunicationSymbol(id: "ask", assetName: "ask", displayLabel: "Ask", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "assembly", assetName: "assembly", displayLabel: "Assembly", category: "Work & School", rawCategory: "Work and School Timetable"),
    CommunicationSymbol(id: "assistance", assetName: "assistance", displayLabel: "Assistance", category: "People & Places", rawCategory: "People Profession"),
    CommunicationSymbol(id: "atom", assetName: "atom", displayLabel: "Atom", category: "Science & Learning", rawCategory: "Science"),
    CommunicationSymbol(id: "autumn", assetName: "autumn", displayLabel: "Autumn", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "awake", assetName: "awake", displayLabel: "Awake", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "away", assetName: "away", displayLabel: "Away", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "baby", assetName: "baby", displayLabel: "Baby", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "backwards", assetName: "backwards", displayLabel: "Backwards", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "bad", assetName: "bad", displayLabel: "Bad", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "badminton", assetName: "badminton", displayLabel: "Badminton", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "bagel", assetName: "bagel", displayLabel: "Bagel", category: "Food & Drink", rawCategory: "Food Breads and baking"),
    CommunicationSymbol(id: "bake", assetName: "bake", displayLabel: "Bake", category: "Food & Drink", rawCategory: "Food Kitchen actions"),
    CommunicationSymbol(id: "ball", assetName: "ball", displayLabel: "Ball", category: "Everyday Objects", rawCategory: "Leisure Toys"),
    CommunicationSymbol(id: "bank", assetName: "bank", displayLabel: "Bank", category: "Everyday Objects", rawCategory: "Money"),
    CommunicationSymbol(id: "bap", assetName: "bap", displayLabel: "Bap", category: "Food & Drink", rawCategory: "Food Breads and baking"),
    CommunicationSymbol(id: "basketball", assetName: "basketball", displayLabel: "Basketball", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "bat", assetName: "bat", displayLabel: "Bat", category: "Animals & Nature", rawCategory: "Animal Mammal"),
    CommunicationSymbol(id: "bath", assetName: "bath", displayLabel: "Bath", category: "People & Places", rawCategory: "Building Contents"),
    CommunicationSymbol(id: "bathe", assetName: "bathe", displayLabel: "Bathe", category: "Body & Health", rawCategory: "Healthcare Grooming activities"),
    CommunicationSymbol(id: "beach", assetName: "beach", displayLabel: "Beach", category: "People & Places", rawCategory: "Holiday and travel"),
    CommunicationSymbol(id: "beak", assetName: "beak", displayLabel: "Beak", category: "Animals & Nature", rawCategory: "Animal Features"),
    CommunicationSymbol(id: "bed", assetName: "bed", displayLabel: "Bed", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "beef", assetName: "beef", displayLabel: "Beef", category: "Food & Drink", rawCategory: "Food Meat"),
    CommunicationSymbol(id: "beer", assetName: "beer", displayLabel: "Beer", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "before", assetName: "before", displayLabel: "Before", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "behind", assetName: "behind", displayLabel: "Behind", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "bell", assetName: "bell", displayLabel: "Bell", category: "People & Places", rawCategory: "Building Contents"),
    CommunicationSymbol(id: "below", assetName: "below", displayLabel: "Below", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "bench", assetName: "bench", displayLabel: "Bench", category: "People & Places", rawCategory: "Building Garden and farm"),
    CommunicationSymbol(id: "bendy", assetName: "bendy", displayLabel: "Bendy", category: "Science & Learning", rawCategory: "Science"),
    CommunicationSymbol(id: "between", assetName: "between", displayLabel: "Between", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "bib", assetName: "bib", displayLabel: "Bib", category: "Everyday Objects", rawCategory: "Clothes General"),
    CommunicationSymbol(id: "bingo", assetName: "bingo", displayLabel: "Bingo", category: "Everyday Objects", rawCategory: "Leisure Games"),
    CommunicationSymbol(id: "bird", assetName: "bird", displayLabel: "Bird", category: "Animals & Nature", rawCategory: "Animal Birds"),
    CommunicationSymbol(id: "black", assetName: "black", displayLabel: "Black", category: "Everyday Objects", rawCategory: "Art Colour"),
    CommunicationSymbol(id: "blackboard", assetName: "blackboard", displayLabel: "Blackboard", category: "People & Places", rawCategory: "Building Equipment and devices"),
    CommunicationSymbol(id: "bless", assetName: "bless", displayLabel: "Bless", category: "People & Places", rawCategory: "Religion General"),
    CommunicationSymbol(id: "blue", assetName: "blue", displayLabel: "Blue", category: "Everyday Objects", rawCategory: "Art Colour"),
    CommunicationSymbol(id: "boat", assetName: "boat", displayLabel: "Boat", category: "Everyday Objects", rawCategory: "Transport Water"),
    CommunicationSymbol(id: "bolt", assetName: "bolt", displayLabel: "Bolt", category: "Everyday Objects", rawCategory: "Tools Workshop"),
    CommunicationSymbol(id: "bone", assetName: "bone", displayLabel: "Bone", category: "Animals & Nature", rawCategory: "Animal Activity Feeding"),
    CommunicationSymbol(id: "bonfire", assetName: "bonfire", displayLabel: "Bonfire", category: "People & Places", rawCategory: "Building Garden and farm"),
    CommunicationSymbol(id: "both", assetName: "both", displayLabel: "Both", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "bottom", assetName: "bottom", displayLabel: "Bottom", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "bow", assetName: "bow", displayLabel: "Bow", category: "Everyday Objects", rawCategory: "Clothes Accessories"),
    CommunicationSymbol(id: "bowl", assetName: "bowl", displayLabel: "Bowl", category: "Food & Drink", rawCategory: "Food Kitchen items"),
    CommunicationSymbol(id: "box", assetName: "box", displayLabel: "Box", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "bra", assetName: "bra", displayLabel: "Bra", category: "Everyday Objects", rawCategory: "Clothes General"),
    CommunicationSymbol(id: "brazil", assetName: "brazil", displayLabel: "Brazil", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "break", assetName: "break", displayLabel: "Break", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "bridle", assetName: "bridle", displayLabel: "Bridle", category: "Animals & Nature", rawCategory: "Animal Activity Grooming"),
    CommunicationSymbol(id: "bright", assetName: "bright", displayLabel: "Bright", category: "Everyday Objects", rawCategory: "Electrical General"),
    CommunicationSymbol(id: "broken", assetName: "broken", displayLabel: "Broken", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "brooch", assetName: "brooch", displayLabel: "Brooch", category: "Everyday Objects", rawCategory: "Clothes Jewellery"),
    CommunicationSymbol(id: "buckle", assetName: "buckle", displayLabel: "Buckle", category: "Everyday Objects", rawCategory: "Clothes Accessories"),
    CommunicationSymbol(id: "bud", assetName: "bud", displayLabel: "Bud", category: "Animals & Nature", rawCategory: "Plants and Trees"),
    CommunicationSymbol(id: "bumpy", assetName: "bumpy", displayLabel: "Bumpy", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "burn", assetName: "burn", displayLabel: "Burn", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "bus", assetName: "bus", displayLabel: "Bus", category: "Everyday Objects", rawCategory: "Leisure Toys"),
    CommunicationSymbol(id: "bush", assetName: "bush", displayLabel: "Bush", category: "Animals & Nature", rawCategory: "Plants and Trees"),
    CommunicationSymbol(id: "busy", assetName: "busy", displayLabel: "Busy", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "butter", assetName: "butter", displayLabel: "Butter", category: "Food & Drink", rawCategory: "Food Dairy"),
    CommunicationSymbol(id: "cafe", assetName: "cafe", displayLabel: "Cafe", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "cage", assetName: "cage", displayLabel: "Cage", category: "Animals & Nature", rawCategory: "Animal Habitat"),
    CommunicationSymbol(id: "cake", assetName: "cake", displayLabel: "Cake", category: "Food & Drink", rawCategory: "Food Breads and baking"),
    CommunicationSymbol(id: "calendar", assetName: "calendar", displayLabel: "Calendar", category: "Work & School", rawCategory: "Work and School Timetable"),
    CommunicationSymbol(id: "call", assetName: "call", displayLabel: "Call", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "camera", assetName: "camera", displayLabel: "Camera", category: "Everyday Objects", rawCategory: "Electrical Media"),
    CommunicationSymbol(id: "canada", assetName: "canada", displayLabel: "Canada", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "canoe", assetName: "canoe", displayLabel: "Canoe", category: "Everyday Objects", rawCategory: "Transport Water"),
    CommunicationSymbol(id: "cap", assetName: "cap", displayLabel: "Cap", category: "Everyday Objects", rawCategory: "Clothes General"),
    CommunicationSymbol(id: "car", assetName: "car", displayLabel: "Car", category: "Everyday Objects", rawCategory: "Transport Road"),
    CommunicationSymbol(id: "carbohydrates", assetName: "carbohydrates", displayLabel: "Carbohydrates", category: "Food & Drink", rawCategory: "Food Diet"),
    CommunicationSymbol(id: "card", assetName: "card", displayLabel: "Card", category: "Celebrations", rawCategory: "Celebration Item"),
    CommunicationSymbol(id: "cart", assetName: "cart", displayLabel: "Cart", category: "Everyday Objects", rawCategory: "Transport Road"),
    CommunicationSymbol(id: "cashew", assetName: "cashew", displayLabel: "Cashew", category: "Food & Drink", rawCategory: "Food Nuts"),
    CommunicationSymbol(id: "castle", assetName: "castle", displayLabel: "Castle", category: "People & Places", rawCategory: "Building Public"),
    CommunicationSymbol(id: "cat", assetName: "cat", displayLabel: "Cat", category: "Animals & Nature", rawCategory: "Animal Mammal"),
    CommunicationSymbol(id: "cctv", assetName: "cctv", displayLabel: "Cctv", category: "Everyday Objects", rawCategory: "Electrical Media"),
    CommunicationSymbol(id: "celebration", assetName: "celebration", displayLabel: "Celebration", category: "Celebrations", rawCategory: "Celebration Event"),
    CommunicationSymbol(id: "chair", assetName: "chair", displayLabel: "Chair", category: "People & Places", rawCategory: "Building Furniture"),
    CommunicationSymbol(id: "chalk", assetName: "chalk", displayLabel: "Chalk", category: "Work & School", rawCategory: "Work and School Stationery"),
    CommunicationSymbol(id: "cheese", assetName: "cheese", displayLabel: "Cheese", category: "Food & Drink", rawCategory: "Food Dairy"),
    CommunicationSymbol(id: "chicken", assetName: "chicken", displayLabel: "Chicken", category: "Food & Drink", rawCategory: "Food Poultry"),
    CommunicationSymbol(id: "china", assetName: "china", displayLabel: "China", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "chips", assetName: "chips", displayLabel: "Chips", category: "Food & Drink", rawCategory: "Food Vegetables and salads"),
    CommunicationSymbol(id: "chop", assetName: "chop", displayLabel: "Chop", category: "Food & Drink", rawCategory: "Food Kitchen actions"),
    CommunicationSymbol(id: "church", assetName: "church", displayLabel: "Church", category: "People & Places", rawCategory: "Building Public"),
    CommunicationSymbol(id: "cigarette", assetName: "cigarette", displayLabel: "Cigarette", category: "Everyday Objects", rawCategory: "Leisure General"),
    CommunicationSymbol(id: "circle", assetName: "circle", displayLabel: "Circle", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "claw", assetName: "claw", displayLabel: "Claw", category: "Animals & Nature", rawCategory: "Animal Features"),
    CommunicationSymbol(id: "clay", assetName: "clay", displayLabel: "Clay", category: "Science & Learning", rawCategory: "Science"),
    CommunicationSymbol(id: "clipboard", assetName: "clipboard", displayLabel: "Clipboard", category: "Everyday Objects", rawCategory: "Art Making"),
    CommunicationSymbol(id: "clock", assetName: "clock", displayLabel: "Clock", category: "Everyday Objects", rawCategory: "Electrical General"),
    CommunicationSymbol(id: "closed", assetName: "closed", displayLabel: "Closed", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "cloudy", assetName: "cloudy", displayLabel: "Cloudy", category: "Animals & Nature", rawCategory: "Environment Weather"),
    CommunicationSymbol(id: "coffee", assetName: "coffee", displayLabel: "Coffee", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "cold", assetName: "cold", displayLabel: "Cold", category: "Food & Drink", rawCategory: "Drink Description"),
    CommunicationSymbol(id: "comb", assetName: "comb", displayLabel: "Comb", category: "Body & Health", rawCategory: "Healthcare Grooming items"),
    CommunicationSymbol(id: "comet", assetName: "comet", displayLabel: "Comet", category: "Science & Learning", rawCategory: "Science Astronomy"),
    CommunicationSymbol(id: "cook", assetName: "cook", displayLabel: "Cook", category: "Food & Drink", rawCategory: "Food Kitchen actions"),
    CommunicationSymbol(id: "copy", assetName: "copy", displayLabel: "Copy", category: "Everyday Objects", rawCategory: "Computer Icon"),
    CommunicationSymbol(id: "correct", assetName: "correct", displayLabel: "Correct", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "cot", assetName: "cot", displayLabel: "Cot", category: "People & Places", rawCategory: "Building Furniture"),
    CommunicationSymbol(id: "counters", assetName: "counters", displayLabel: "Counters", category: "Everyday Objects", rawCategory: "Money"),
    CommunicationSymbol(id: "cow", assetName: "cow", displayLabel: "Cow", category: "Animals & Nature", rawCategory: "Animal Mammal"),
    CommunicationSymbol(id: "crab", assetName: "crab", displayLabel: "Crab", category: "Animals & Nature", rawCategory: "Animal Crustacean and Molluscs"),
    CommunicationSymbol(id: "cream", assetName: "cream", displayLabel: "Cream", category: "Food & Drink", rawCategory: "Food Dairy"),
    CommunicationSymbol(id: "cricket", assetName: "cricket", displayLabel: "Cricket", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "crooked", assetName: "crooked", displayLabel: "Crooked", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "cross", assetName: "cross", displayLabel: "Cross", category: "People & Places", rawCategory: "Religion General"),
    CommunicationSymbol(id: "cruiser", assetName: "cruiser", displayLabel: "Cruiser", category: "Everyday Objects", rawCategory: "Transport Water"),
    CommunicationSymbol(id: "curly", assetName: "curly", displayLabel: "Curly", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "curry", assetName: "curry", displayLabel: "Curry", category: "Food & Drink", rawCategory: "Food Meals and snacks"),
    CommunicationSymbol(id: "cut", assetName: "cut", displayLabel: "Cut", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "darts", assetName: "darts", displayLabel: "Darts", category: "Everyday Objects", rawCategory: "Leisure Games"),
    CommunicationSymbol(id: "date", assetName: "date", displayLabel: "Date", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "day", assetName: "day", displayLabel: "Day", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "dead", assetName: "dead", displayLabel: "Dead", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "deep", assetName: "deep", displayLabel: "Deep", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "desk", assetName: "desk", displayLabel: "Desk", category: "People & Places", rawCategory: "Building Furniture"),
    CommunicationSymbol(id: "diamond", assetName: "diamond", displayLabel: "Diamond", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "die", assetName: "die", displayLabel: "Die", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "dirty", assetName: "dirty", displayLabel: "Dirty", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "disability", assetName: "disability", displayLabel: "Disability", category: "Communication", rawCategory: "Communication Signs"),
    CommunicationSymbol(id: "disabled", assetName: "disabled", displayLabel: "Disabled", category: "Communication", rawCategory: "Communication Signs"),
    CommunicationSymbol(id: "dishwasher", assetName: "dishwasher", displayLabel: "Dishwasher", category: "People & Places", rawCategory: "Building Equipment and devices"),
    CommunicationSymbol(id: "divide", assetName: "divide", displayLabel: "Divide", category: "Communication", rawCategory: "Number Activity"),
    CommunicationSymbol(id: "doctor", assetName: "doctor", displayLabel: "Doctor", category: "People & Places", rawCategory: "People Profession"),
    CommunicationSymbol(id: "dog", assetName: "dog", displayLabel: "Dog", category: "Animals & Nature", rawCategory: "Animal Mammal"),
    CommunicationSymbol(id: "doll", assetName: "doll", displayLabel: "Doll", category: "Everyday Objects", rawCategory: "Leisure Toys"),
    CommunicationSymbol(id: "dolphin", assetName: "dolphin", displayLabel: "Dolphin", category: "Animals & Nature", rawCategory: "Animal Fish and Marine mammals"),
    CommunicationSymbol(id: "door", assetName: "door", displayLabel: "Door", category: "People & Places", rawCategory: "Building Structure"),
    CommunicationSymbol(id: "dove", assetName: "dove", displayLabel: "Dove", category: "Animals & Nature", rawCategory: "Animal Birds"),
    CommunicationSymbol(id: "down", assetName: "down", displayLabel: "Down", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "drama", assetName: "drama", displayLabel: "Drama", category: "Work & School", rawCategory: "Work and School Subjects"),
    CommunicationSymbol(id: "drink", assetName: "drink", displayLabel: "Drink", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "drinks", assetName: "drinks", displayLabel: "Drinks", category: "Food & Drink", rawCategory: "Drink Description"),
    CommunicationSymbol(id: "drum", assetName: "drum", displayLabel: "Drum", category: "Everyday Objects", rawCategory: "Music Instrument"),
    CommunicationSymbol(id: "dry", assetName: "dry", displayLabel: "Dry", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "duck", assetName: "duck", displayLabel: "Duck", category: "Animals & Nature", rawCategory: "Animal Birds"),
    CommunicationSymbol(id: "dust", assetName: "dust", displayLabel: "Dust", category: "People & Places", rawCategory: "Building Household tasks"),
    CommunicationSymbol(id: "ear", assetName: "ear", displayLabel: "Ear", category: "Body & Health", rawCategory: "Healthcare Body parts"),
    CommunicationSymbol(id: "earrings", assetName: "earrings", displayLabel: "Earrings", category: "Everyday Objects", rawCategory: "Clothes Jewellery"),
    CommunicationSymbol(id: "earthworm", assetName: "earthworm", displayLabel: "Earthworm", category: "Animals & Nature", rawCategory: "Animal Other Invertebrates"),
    CommunicationSymbol(id: "east", assetName: "east", displayLabel: "East", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "egg", assetName: "egg", displayLabel: "Egg", category: "Food & Drink", rawCategory: "Food Eggs"),
    CommunicationSymbol(id: "eggs", assetName: "eggs", displayLabel: "Eggs", category: "Food & Drink", rawCategory: "Food Eggs"),
    CommunicationSymbol(id: "egypt", assetName: "egypt", displayLabel: "Egypt", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "eighth", assetName: "eighth", displayLabel: "Eighth", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "either", assetName: "either", displayLabel: "Either", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "elearning", assetName: "elearning", displayLabel: "Elearning", category: "Everyday Objects", rawCategory: "Electrical Computer"),
    CommunicationSymbol(id: "elf", assetName: "elf", displayLabel: "Elf", category: "Celebrations", rawCategory: "Celebration Item"),
    CommunicationSymbol(id: "email", assetName: "email", displayLabel: "Email", category: "Everyday Objects", rawCategory: "Computer Icon"),
    CommunicationSymbol(id: "empty", assetName: "empty", displayLabel: "Empty", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "england", assetName: "england", displayLabel: "England", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "enough", assetName: "enough", displayLabel: "Enough", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "enter", assetName: "enter", displayLabel: "Enter", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "even", assetName: "even", displayLabel: "Even", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "every", assetName: "every", displayLabel: "Every", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "exit", assetName: "exit", displayLabel: "Exit", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "extra", assetName: "extra", displayLabel: "Extra", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "eye", assetName: "eye", displayLabel: "Eye", category: "Body & Health", rawCategory: "Healthcare Body parts"),
    CommunicationSymbol(id: "family", assetName: "family", displayLabel: "Family", category: "People & Places", rawCategory: "People Relationship"),
    CommunicationSymbol(id: "fancy", assetName: "fancy", displayLabel: "Fancy", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "fat", assetName: "fat", displayLabel: "Fat", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "fats", assetName: "fats", displayLabel: "Fats", category: "Food & Drink", rawCategory: "Food Diet"),
    CommunicationSymbol(id: "favourite", assetName: "favourite", displayLabel: "Favourite", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "ferry", assetName: "ferry", displayLabel: "Ferry", category: "Everyday Objects", rawCategory: "Transport Water"),
    CommunicationSymbol(id: "field", assetName: "field", displayLabel: "Field", category: "People & Places", rawCategory: "Building Garden and farm"),
    CommunicationSymbol(id: "fig", assetName: "fig", displayLabel: "Fig", category: "Food & Drink", rawCategory: "Food Fruit"),
    CommunicationSymbol(id: "file", assetName: "file", displayLabel: "File", category: "Everyday Objects", rawCategory: "Tools Workshop"),
    CommunicationSymbol(id: "fin", assetName: "fin", displayLabel: "Fin", category: "Animals & Nature", rawCategory: "Animal Features"),
    CommunicationSymbol(id: "finish", assetName: "finish", displayLabel: "Finish", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "fire", assetName: "fire", displayLabel: "Fire", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "first", assetName: "first", displayLabel: "First", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "fish", assetName: "fish", displayLabel: "Fish", category: "Animals & Nature", rawCategory: "Animal Fish and Marine mammals"),
    CommunicationSymbol(id: "flame", assetName: "flame", displayLabel: "Flame", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "flat", assetName: "flat", displayLabel: "Flat", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "floor", assetName: "floor", displayLabel: "Floor", category: "People & Places", rawCategory: "Building Structure"),
    CommunicationSymbol(id: "flute", assetName: "flute", displayLabel: "Flute", category: "Everyday Objects", rawCategory: "Music Instrument"),
    CommunicationSymbol(id: "fly", assetName: "fly", displayLabel: "Fly", category: "Animals & Nature", rawCategory: "Animal Spiders and Insects"),
    CommunicationSymbol(id: "food", assetName: "food", displayLabel: "Food", category: "Food & Drink", rawCategory: "Food Breads and baking"),
    CommunicationSymbol(id: "football", assetName: "football", displayLabel: "Football", category: "Everyday Objects", rawCategory: "Sport Accessories"),
    CommunicationSymbol(id: "forward", assetName: "forward", displayLabel: "Forward", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "forwards", assetName: "forwards", displayLabel: "Forwards", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "france", assetName: "france", displayLabel: "France", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "frog", assetName: "frog", displayLabel: "Frog", category: "Animals & Nature", rawCategory: "Animal Reptiles and Amphibians"),
    CommunicationSymbol(id: "fry", assetName: "fry", displayLabel: "Fry", category: "Food & Drink", rawCategory: "Food Kitchen actions"),
    CommunicationSymbol(id: "full", assetName: "full", displayLabel: "Full", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "future", assetName: "future", displayLabel: "Future", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "fuzzy", assetName: "fuzzy", displayLabel: "Fuzzy", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "garage", assetName: "garage", displayLabel: "Garage", category: "People & Places", rawCategory: "Building Residential"),
    CommunicationSymbol(id: "germany", assetName: "germany", displayLabel: "Germany", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "glass", assetName: "glass", displayLabel: "Glass", category: "Science & Learning", rawCategory: "Science"),
    CommunicationSymbol(id: "globe", assetName: "globe", displayLabel: "Globe", category: "Work & School", rawCategory: "Work and School Education"),
    CommunicationSymbol(id: "glue", assetName: "glue", displayLabel: "Glue", category: "Work & School", rawCategory: "Work and School Stationery"),
    CommunicationSymbol(id: "gnat", assetName: "gnat", displayLabel: "Gnat", category: "Animals & Nature", rawCategory: "Animal Spiders and Insects"),
    CommunicationSymbol(id: "go", assetName: "go", displayLabel: "Go", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "goal", assetName: "goal", displayLabel: "Goal", category: "Everyday Objects", rawCategory: "Sport Accessories"),
    CommunicationSymbol(id: "golf", assetName: "golf", displayLabel: "Golf", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "good", assetName: "good", displayLabel: "Good", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "great", assetName: "great", displayLabel: "Great", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "greece", assetName: "greece", displayLabel: "Greece", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "guitar", assetName: "guitar", displayLabel: "Guitar", category: "Everyday Objects", rawCategory: "Music Instrument"),
    CommunicationSymbol(id: "gum", assetName: "gum", displayLabel: "Gum", category: "Body & Health", rawCategory: "Healthcare Body parts"),
    CommunicationSymbol(id: "guy", assetName: "guy", displayLabel: "Guy", category: "Celebrations", rawCategory: "Celebration Item"),
    CommunicationSymbol(id: "half", assetName: "half", displayLabel: "Half", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "halloween", assetName: "halloween", displayLabel: "Halloween", category: "Celebrations", rawCategory: "Celebration Event"),
    CommunicationSymbol(id: "ham", assetName: "ham", displayLabel: "Ham", category: "Food & Drink", rawCategory: "Food Meat"),
    CommunicationSymbol(id: "hangar", assetName: "hangar", displayLabel: "Hangar", category: "Everyday Objects", rawCategory: "Transport Air"),
    CommunicationSymbol(id: "happy", assetName: "happy", displayLabel: "Happy", category: "Feelings & Descriptions", rawCategory: "People Feelings"),
    CommunicationSymbol(id: "hard", assetName: "hard", displayLabel: "Hard", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "headache", assetName: "headache", displayLabel: "Headache", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "headmouse", assetName: "headmouse", displayLabel: "Headmouse", category: "Communication", rawCategory: "Communication Aid"),
    CommunicationSymbol(id: "heavy", assetName: "heavy", displayLabel: "Heavy", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "helicopter", assetName: "helicopter", displayLabel: "Helicopter", category: "Everyday Objects", rawCategory: "Transport Air"),
    CommunicationSymbol(id: "hello", assetName: "hello", displayLabel: "Hello", category: "Communication", rawCategory: "Communication Conversation"),
    CommunicationSymbol(id: "helmet", assetName: "helmet", displayLabel: "Helmet", category: "Everyday Objects", rawCategory: "Clothes Sport"),
    CommunicationSymbol(id: "help", assetName: "help", displayLabel: "Help", category: "Actions", rawCategory: "Verb"),
    CommunicationSymbol(id: "heptagon", assetName: "heptagon", displayLabel: "Heptagon", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "hexagon", assetName: "hexagon", displayLabel: "Hexagon", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "high", assetName: "high", displayLabel: "High", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "highest", assetName: "highest", displayLabel: "Highest", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "hoe", assetName: "hoe", displayLabel: "Hoe", category: "Everyday Objects", rawCategory: "Tools Garden"),
    CommunicationSymbol(id: "hoist", assetName: "hoist", displayLabel: "Hoist", category: "Body & Health", rawCategory: "Healthcare Medical items"),
    CommunicationSymbol(id: "holdall", assetName: "holdall", displayLabel: "Holdall", category: "People & Places", rawCategory: "Holiday and travel"),
    CommunicationSymbol(id: "hollow", assetName: "hollow", displayLabel: "Hollow", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "home", assetName: "home", displayLabel: "Home", category: "People & Places", rawCategory: "Building Residential"),
    CommunicationSymbol(id: "honey", assetName: "honey", displayLabel: "Honey", category: "Food & Drink", rawCategory: "Food Ingredients"),
    CommunicationSymbol(id: "hoover", assetName: "hoover", displayLabel: "Hoover", category: "People & Places", rawCategory: "Building Household tasks"),
    CommunicationSymbol(id: "hose", assetName: "hose", displayLabel: "Hose", category: "Everyday Objects", rawCategory: "Tools Garden"),
    CommunicationSymbol(id: "hot", assetName: "hot", displayLabel: "Hot", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "house", assetName: "house", displayLabel: "House", category: "People & Places", rawCategory: "Building Residential"),
    CommunicationSymbol(id: "how", assetName: "how", displayLabel: "How", category: "Feelings & Descriptions", rawCategory: "Question"),
    CommunicationSymbol(id: "hungry", assetName: "hungry", displayLabel: "Hungry", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "in", assetName: "in", displayLabel: "In", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "inbox", assetName: "inbox", displayLabel: "Inbox", category: "Everyday Objects", rawCategory: "Computer Icon"),
    CommunicationSymbol(id: "india", assetName: "india", displayLabel: "India", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "intellikeys", assetName: "intellikeys", displayLabel: "Intellikeys", category: "Communication", rawCategory: "Communication Aid"),
    CommunicationSymbol(id: "iphone", assetName: "iphone", displayLabel: "Iphone", category: "Everyday Objects", rawCategory: "Electrical Phone"),
    CommunicationSymbol(id: "ipod", assetName: "ipod", displayLabel: "Ipod", category: "Everyday Objects", rawCategory: "Electrical Media"),
    CommunicationSymbol(id: "ireland", assetName: "ireland", displayLabel: "Ireland", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "iron", assetName: "iron", displayLabel: "Iron", category: "People & Places", rawCategory: "Building Contents"),
    CommunicationSymbol(id: "italy", assetName: "italy", displayLabel: "Italy", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "itch", assetName: "itch", displayLabel: "Itch", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "ivy", assetName: "ivy", displayLabel: "Ivy", category: "Animals & Nature", rawCategory: "Plants and Trees"),
    CommunicationSymbol(id: "jam", assetName: "jam", displayLabel: "Jam", category: "Food & Drink", rawCategory: "Food Sweets and desserts"),
    CommunicationSymbol(id: "jamaica", assetName: "jamaica", displayLabel: "Jamaica", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "japan", assetName: "japan", displayLabel: "Japan", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "jar", assetName: "jar", displayLabel: "Jar", category: "Food & Drink", rawCategory: "Food Kitchen items"),
    CommunicationSymbol(id: "jeep", assetName: "jeep", displayLabel: "Jeep", category: "Everyday Objects", rawCategory: "Transport Road"),
    CommunicationSymbol(id: "jelly", assetName: "jelly", displayLabel: "Jelly", category: "Food & Drink", rawCategory: "Food Sweets and desserts"),
    CommunicationSymbol(id: "jellyfish", assetName: "jellyfish", displayLabel: "Jellyfish", category: "Animals & Nature", rawCategory: "Animal Other Invertebrates"),
    CommunicationSymbol(id: "jesus", assetName: "jesus", displayLabel: "Jesus", category: "People & Places", rawCategory: "Religion Person"),
    CommunicationSymbol(id: "judas", assetName: "judas", displayLabel: "Judas", category: "People & Places", rawCategory: "Religion Person"),
    CommunicationSymbol(id: "judo", assetName: "judo", displayLabel: "Judo", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "kennel", assetName: "kennel", displayLabel: "Kennel", category: "Animals & Nature", rawCategory: "Animal Habitat"),
    CommunicationSymbol(id: "kite", assetName: "kite", displayLabel: "Kite", category: "Everyday Objects", rawCategory: "Leisure Toys"),
    CommunicationSymbol(id: "kiwi", assetName: "kiwi", displayLabel: "Kiwi", category: "Food & Drink", rawCategory: "Food Fruit"),
    CommunicationSymbol(id: "lamb", assetName: "lamb", displayLabel: "Lamb", category: "Food & Drink", rawCategory: "Food Meat"),
    CommunicationSymbol(id: "lamp", assetName: "lamp", displayLabel: "Lamp", category: "Everyday Objects", rawCategory: "Electrical General"),
    CommunicationSymbol(id: "laptop", assetName: "laptop", displayLabel: "Laptop", category: "Everyday Objects", rawCategory: "Electrical Computer"),
    CommunicationSymbol(id: "large", assetName: "large", displayLabel: "Large", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "last", assetName: "last", displayLabel: "Last", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "lead", assetName: "lead", displayLabel: "Lead", category: "Animals & Nature", rawCategory: "Animal Activity Grooming"),
    CommunicationSymbol(id: "leek", assetName: "leek", displayLabel: "Leek", category: "Food & Drink", rawCategory: "Food Vegetables and salads"),
    CommunicationSymbol(id: "left", assetName: "left", displayLabel: "Left", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "lens", assetName: "lens", displayLabel: "Lens", category: "Science & Learning", rawCategory: "Science"),
    CommunicationSymbol(id: "lent", assetName: "lent", displayLabel: "Lent", category: "People & Places", rawCategory: "Religion Festival"),
    CommunicationSymbol(id: "lid", assetName: "lid", displayLabel: "Lid", category: "Food & Drink", rawCategory: "Food Kitchen items"),
    CommunicationSymbol(id: "lift", assetName: "lift", displayLabel: "Lift", category: "People & Places", rawCategory: "Building Structure"),
    CommunicationSymbol(id: "light", assetName: "light", displayLabel: "Light", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "lime", assetName: "lime", displayLabel: "Lime", category: "Food & Drink", rawCategory: "Food Fruit"),
    CommunicationSymbol(id: "little", assetName: "little", displayLabel: "Little", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "lizard", assetName: "lizard", displayLabel: "Lizard", category: "Animals & Nature", rawCategory: "Animal Reptiles and Amphibians"),
    CommunicationSymbol(id: "log", assetName: "log", displayLabel: "Log", category: "Animals & Nature", rawCategory: "Plants and Trees"),
    CommunicationSymbol(id: "long", assetName: "long", displayLabel: "Long", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "lost", assetName: "lost", displayLabel: "Lost", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "loud", assetName: "loud", displayLabel: "Loud", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "love", assetName: "love", displayLabel: "Love", category: "Feelings & Descriptions", rawCategory: "People Feelings"),
    CommunicationSymbol(id: "lowest", assetName: "lowest", displayLabel: "Lowest", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "lucky", assetName: "lucky", displayLabel: "Lucky", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "lump", assetName: "lump", displayLabel: "Lump", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "manger", assetName: "manger", displayLabel: "Manger", category: "People & Places", rawCategory: "Religion General"),
    CommunicationSymbol(id: "marmite", assetName: "marmite", displayLabel: "Marmite", category: "Food & Drink", rawCategory: "Food Ingredients"),
    CommunicationSymbol(id: "mars", assetName: "mars", displayLabel: "Mars", category: "Science & Learning", rawCategory: "Science Astronomy"),
    CommunicationSymbol(id: "mary", assetName: "mary", displayLabel: "Mary", category: "People & Places", rawCategory: "Religion Person"),
    CommunicationSymbol(id: "maths", assetName: "maths", displayLabel: "Maths", category: "Work & School", rawCategory: "Work and School Subjects"),
    CommunicationSymbol(id: "meat", assetName: "meat", displayLabel: "Meat", category: "Food & Drink", rawCategory: "Food Meat"),
    CommunicationSymbol(id: "medal", assetName: "medal", displayLabel: "Medal", category: "Everyday Objects", rawCategory: "Sport Accessories"),
    CommunicationSymbol(id: "medicine", assetName: "medicine", displayLabel: "Medicine", category: "Body & Health", rawCategory: "Healthcare Medical items"),
    CommunicationSymbol(id: "mend", assetName: "mend", displayLabel: "Mend", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "menu", assetName: "menu", displayLabel: "Menu", category: "Food & Drink", rawCategory: "Food Meals and snacks"),
    CommunicationSymbol(id: "mexico", assetName: "mexico", displayLabel: "Mexico", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "middle", assetName: "middle", displayLabel: "Middle", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "milk", assetName: "milk", displayLabel: "Milk", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "mints", assetName: "mints", displayLabel: "Mints", category: "Food & Drink", rawCategory: "Food Sweets and desserts"),
    CommunicationSymbol(id: "minute", assetName: "minute", displayLabel: "Minute", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "money", assetName: "money", displayLabel: "Money", category: "Everyday Objects", rawCategory: "Money"),
    CommunicationSymbol(id: "moon", assetName: "moon", displayLabel: "Moon", category: "Science & Learning", rawCategory: "Science Astronomy"),
    CommunicationSymbol(id: "mop", assetName: "mop", displayLabel: "Mop", category: "People & Places", rawCategory: "Building Contents"),
    CommunicationSymbol(id: "more", assetName: "more", displayLabel: "More", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "morning", assetName: "morning", displayLabel: "Morning", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "morocco", assetName: "morocco", displayLabel: "Morocco", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "most", assetName: "most", displayLabel: "Most", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "moth", assetName: "moth", displayLabel: "Moth", category: "Animals & Nature", rawCategory: "Animal Spiders and Insects"),
    CommunicationSymbol(id: "music", assetName: "music", displayLabel: "Music", category: "Work & School", rawCategory: "Work and School Subjects"),
    CommunicationSymbol(id: "nail", assetName: "nail", displayLabel: "Nail", category: "Everyday Objects", rawCategory: "Tools Workshop"),
    CommunicationSymbol(id: "nappy", assetName: "nappy", displayLabel: "Nappy", category: "Body & Health", rawCategory: "Healthcare Grooming items"),
    CommunicationSymbol(id: "nativity", assetName: "nativity", displayLabel: "Nativity", category: "People & Places", rawCategory: "Religion Festival"),
    CommunicationSymbol(id: "near", assetName: "near", displayLabel: "Near", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "neither", assetName: "neither", displayLabel: "Neither", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "nest", assetName: "nest", displayLabel: "Nest", category: "Animals & Nature", rawCategory: "Animal Habitat"),
    CommunicationSymbol(id: "newspaper", assetName: "newspaper", displayLabel: "Newspaper", category: "Work & School", rawCategory: "Work and School Education"),
    CommunicationSymbol(id: "next", assetName: "next", displayLabel: "Next", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "nigeria", assetName: "nigeria", displayLabel: "Nigeria", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "night", assetName: "night", displayLabel: "Night", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "no", assetName: "no", displayLabel: "No", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "noisy", assetName: "noisy", displayLabel: "Noisy", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "noodles", assetName: "noodles", displayLabel: "Noodles", category: "Food & Drink", rawCategory: "Food Pastas and rice"),
    CommunicationSymbol(id: "north", assetName: "north", displayLabel: "North", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "now", assetName: "now", displayLabel: "Now", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "nurse", assetName: "nurse", displayLabel: "Nurse", category: "People & Places", rawCategory: "People Profession"),
    CommunicationSymbol(id: "nuts", assetName: "nuts", displayLabel: "Nuts", category: "Food & Drink", rawCategory: "Food Nuts"),
    CommunicationSymbol(id: "octagon", assetName: "octagon", displayLabel: "Octagon", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "off", assetName: "off", displayLabel: "Off", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "omelette", assetName: "omelette", displayLabel: "Omelette", category: "Food & Drink", rawCategory: "Food Eggs"),
    CommunicationSymbol(id: "on", assetName: "on", displayLabel: "On", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "one", assetName: "one", displayLabel: "One", category: "Communication", rawCategory: "Number"),
    CommunicationSymbol(id: "open", assetName: "open", displayLabel: "Open", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "opposite", assetName: "opposite", displayLabel: "Opposite", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "out", assetName: "out", displayLabel: "Out", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "outside", assetName: "outside", displayLabel: "Outside", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "oval", assetName: "oval", displayLabel: "Oval", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "over", assetName: "over", displayLabel: "Over", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "owl", assetName: "owl", displayLabel: "Owl", category: "Animals & Nature", rawCategory: "Animal Birds"),
    CommunicationSymbol(id: "pakistan", assetName: "pakistan", displayLabel: "Pakistan", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "paper", assetName: "paper", displayLabel: "Paper", category: "Work & School", rawCategory: "Work and School Stationery"),
    CommunicationSymbol(id: "parachute", assetName: "parachute", displayLabel: "Parachute", category: "Everyday Objects", rawCategory: "Transport Air"),
    CommunicationSymbol(id: "parallelogram", assetName: "parallelogram", displayLabel: "Parallelogram", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "part", assetName: "part", displayLabel: "Part", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "past", assetName: "past", displayLabel: "Past", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "pasta", assetName: "pasta", displayLabel: "Pasta", category: "Food & Drink", rawCategory: "Food Pastas and rice"),
    CommunicationSymbol(id: "pate", assetName: "pate", displayLabel: "Pate", category: "Food & Drink", rawCategory: "Food Meals and snacks"),
    CommunicationSymbol(id: "paw", assetName: "paw", displayLabel: "Paw", category: "Animals & Nature", rawCategory: "Animal Features"),
    CommunicationSymbol(id: "pe", assetName: "pe", displayLabel: "Pe", category: "Work & School", rawCategory: "Work and School Subjects"),
    CommunicationSymbol(id: "pea", assetName: "pea", displayLabel: "Pea", category: "Food & Drink", rawCategory: "Food Vegetables and salads"),
    CommunicationSymbol(id: "pear", assetName: "pear", displayLabel: "Pear", category: "Food & Drink", rawCategory: "Food Fruit"),
    CommunicationSymbol(id: "peas", assetName: "peas", displayLabel: "Peas", category: "Food & Drink", rawCategory: "Food Vegetables and salads"),
    CommunicationSymbol(id: "pecan", assetName: "pecan", displayLabel: "Pecan", category: "Food & Drink", rawCategory: "Food Nuts"),
    CommunicationSymbol(id: "pen", assetName: "pen", displayLabel: "Pen", category: "Work & School", rawCategory: "Work and School Stationery"),
    CommunicationSymbol(id: "pentagon", assetName: "pentagon", displayLabel: "Pentagon", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "perm", assetName: "perm", displayLabel: "Perm", category: "Body & Health", rawCategory: "Healthcare Grooming activities"),
    CommunicationSymbol(id: "permeable", assetName: "permeable", displayLabel: "Permeable", category: "Science & Learning", rawCategory: "Science Eco"),
    CommunicationSymbol(id: "photocopier", assetName: "photocopier", displayLabel: "Photocopier", category: "People & Places", rawCategory: "Building Equipment and devices"),
    CommunicationSymbol(id: "piano", assetName: "piano", displayLabel: "Piano", category: "Everyday Objects", rawCategory: "Music Instrument"),
    CommunicationSymbol(id: "pie", assetName: "pie", displayLabel: "Pie", category: "Food & Drink", rawCategory: "Food Breads and baking"),
    CommunicationSymbol(id: "pink", assetName: "pink", displayLabel: "Pink", category: "Everyday Objects", rawCategory: "Art Colour"),
    CommunicationSymbol(id: "pint", assetName: "pint", displayLabel: "Pint", category: "Food & Drink", rawCategory: "Drink Containers and measures"),
    CommunicationSymbol(id: "point", assetName: "point", displayLabel: "Point", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "pointed", assetName: "pointed", displayLabel: "Pointed", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "poland", assetName: "poland", displayLabel: "Poland", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "pond", assetName: "pond", displayLabel: "Pond", category: "People & Places", rawCategory: "Building Garden and farm"),
    CommunicationSymbol(id: "portugal", assetName: "portugal", displayLabel: "Portugal", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "pot", assetName: "pot", displayLabel: "Pot", category: "Everyday Objects", rawCategory: "Tools Garden"),
    CommunicationSymbol(id: "poultry", assetName: "poultry", displayLabel: "Poultry", category: "Food & Drink", rawCategory: "Food Poultry"),
    CommunicationSymbol(id: "prawn", assetName: "prawn", displayLabel: "Prawn", category: "Animals & Nature", rawCategory: "Animal Crustacean and Molluscs"),
    CommunicationSymbol(id: "pray", assetName: "pray", displayLabel: "Pray", category: "People & Places", rawCategory: "Religion General"),
    CommunicationSymbol(id: "printer", assetName: "printer", displayLabel: "Printer", category: "Everyday Objects", rawCategory: "Electrical Computer"),
    CommunicationSymbol(id: "protein", assetName: "protein", displayLabel: "Protein", category: "Food & Drink", rawCategory: "Food Diet"),
    CommunicationSymbol(id: "purse", assetName: "purse", displayLabel: "Purse", category: "Everyday Objects", rawCategory: "Clothes Accessories"),
    CommunicationSymbol(id: "quadrilateral", assetName: "quadrilateral", displayLabel: "Quadrilateral", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "quarter", assetName: "quarter", displayLabel: "Quarter", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "rain", assetName: "rain", displayLabel: "Rain", category: "Animals & Nature", rawCategory: "Environment Weather"),
    CommunicationSymbol(id: "rainbow", assetName: "rainbow", displayLabel: "Rainbow", category: "Animals & Nature", rawCategory: "Environment Weather"),
    CommunicationSymbol(id: "rake", assetName: "rake", displayLabel: "Rake", category: "Everyday Objects", rawCategory: "Tools Garden"),
    CommunicationSymbol(id: "ramp", assetName: "ramp", displayLabel: "Ramp", category: "Body & Health", rawCategory: "Healthcare Medical items"),
    CommunicationSymbol(id: "ravioli", assetName: "ravioli", displayLabel: "Ravioli", category: "Food & Drink", rawCategory: "Food Pastas and rice"),
    CommunicationSymbol(id: "rectangle", assetName: "rectangle", displayLabel: "Rectangle", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "red", assetName: "red", displayLabel: "Red", category: "Everyday Objects", rawCategory: "Art Colour"),
    CommunicationSymbol(id: "retire", assetName: "retire", displayLabel: "Retire", category: "People & Places", rawCategory: "People Actions"),
    CommunicationSymbol(id: "rhombus", assetName: "rhombus", displayLabel: "Rhombus", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "rice", assetName: "rice", displayLabel: "Rice", category: "Food & Drink", rawCategory: "Food Pastas and rice"),
    CommunicationSymbol(id: "rifle", assetName: "rifle", displayLabel: "Rifle", category: "People & Places", rawCategory: "Military"),
    CommunicationSymbol(id: "right", assetName: "right", displayLabel: "Right", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "ring", assetName: "ring", displayLabel: "Ring", category: "Everyday Objects", rawCategory: "Clothes Jewellery"),
    CommunicationSymbol(id: "risen", assetName: "risen", displayLabel: "Risen", category: "People & Places", rawCategory: "Religion Festival"),
    CommunicationSymbol(id: "road", assetName: "road", displayLabel: "Road", category: "People & Places", rawCategory: "Holiday and travel"),
    CommunicationSymbol(id: "rocket", assetName: "rocket", displayLabel: "Rocket", category: "Everyday Objects", rawCategory: "Transport Space"),
    CommunicationSymbol(id: "room", assetName: "room", displayLabel: "Room", category: "People & Places", rawCategory: "Building Public"),
    CommunicationSymbol(id: "rosette", assetName: "rosette", displayLabel: "Rosette", category: "Everyday Objects", rawCategory: "Sport Accessories"),
    CommunicationSymbol(id: "rug", assetName: "rug", displayLabel: "Rug", category: "People & Places", rawCategory: "Building Contents"),
    CommunicationSymbol(id: "run", assetName: "run", displayLabel: "Run", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "sack", assetName: "sack", displayLabel: "Sack", category: "Celebrations", rawCategory: "Celebration Item"),
    CommunicationSymbol(id: "sad", assetName: "sad", displayLabel: "Sad", category: "Feelings & Descriptions", rawCategory: "People Feelings"),
    CommunicationSymbol(id: "saddle", assetName: "saddle", displayLabel: "Saddle", category: "Animals & Nature", rawCategory: "Animal Activity Grooming"),
    CommunicationSymbol(id: "salad", assetName: "salad", displayLabel: "Salad", category: "Food & Drink", rawCategory: "Food Vegetables and salad"),
    CommunicationSymbol(id: "salty", assetName: "salty", displayLabel: "Salty", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "same", assetName: "same", displayLabel: "Same", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "save", assetName: "save", displayLabel: "Save", category: "Everyday Objects", rawCategory: "Computer Icon"),
    CommunicationSymbol(id: "saw", assetName: "saw", displayLabel: "Saw", category: "Everyday Objects", rawCategory: "Tools Workshop"),
    CommunicationSymbol(id: "scared", assetName: "scared", displayLabel: "Scared", category: "Feelings & Descriptions", rawCategory: "People Feelings"),
    CommunicationSymbol(id: "school", assetName: "school", displayLabel: "School", category: "People & Places", rawCategory: "Building School"),
    CommunicationSymbol(id: "scotland", assetName: "scotland", displayLabel: "Scotland", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "seal", assetName: "seal", displayLabel: "Seal", category: "Animals & Nature", rawCategory: "Animal Fish and Marine mammals"),
    CommunicationSymbol(id: "second", assetName: "second", displayLabel: "Second", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "shallow", assetName: "shallow", displayLabel: "Shallow", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "shapes", assetName: "shapes", displayLabel: "Shapes", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "sharp", assetName: "sharp", displayLabel: "Sharp", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "shave", assetName: "shave", displayLabel: "Shave", category: "Body & Health", rawCategory: "Healthcare Grooming activities"),
    CommunicationSymbol(id: "shells", assetName: "shells", displayLabel: "Shells", category: "Science & Learning", rawCategory: "Science Eco"),
    CommunicationSymbol(id: "shiny", assetName: "shiny", displayLabel: "Shiny", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "shop", assetName: "shop", displayLabel: "Shop", category: "People & Places", rawCategory: "Building Shop"),
    CommunicationSymbol(id: "shrimp", assetName: "shrimp", displayLabel: "Shrimp", category: "Food & Drink", rawCategory: "Food Fish and seafood"),
    CommunicationSymbol(id: "side", assetName: "side", displayLabel: "Side", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "sister", assetName: "sister", displayLabel: "Sister", category: "People & Places", rawCategory: "People Relationship"),
    CommunicationSymbol(id: "six", assetName: "six", displayLabel: "Six", category: "Communication", rawCategory: "Number"),
    CommunicationSymbol(id: "ski", assetName: "ski", displayLabel: "Ski", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "skis", assetName: "skis", displayLabel: "Skis", category: "Everyday Objects", rawCategory: "Sport Accessories"),
    CommunicationSymbol(id: "slice", assetName: "slice", displayLabel: "Slice", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "slide", assetName: "slide", displayLabel: "Slide", category: "Everyday Objects", rawCategory: "Leisure Playground"),
    CommunicationSymbol(id: "sling", assetName: "sling", displayLabel: "Sling", category: "Body & Health", rawCategory: "Healthcare Medical items"),
    CommunicationSymbol(id: "slowly", assetName: "slowly", displayLabel: "Slowly", category: "Animals & Nature", rawCategory: "Animal Reptiles and Amphibians"),
    CommunicationSymbol(id: "slug", assetName: "slug", displayLabel: "Slug", category: "Animals & Nature", rawCategory: "Animal Crustacean and Molluscs"),
    CommunicationSymbol(id: "snail", assetName: "snail", displayLabel: "Snail", category: "Animals & Nature", rawCategory: "Animal Crustacean and Molluscs"),
    CommunicationSymbol(id: "snake", assetName: "snake", displayLabel: "Snake", category: "Animals & Nature", rawCategory: "Animal Reptiles and Amphibians"),
    CommunicationSymbol(id: "snow", assetName: "snow", displayLabel: "Snow", category: "Animals & Nature", rawCategory: "Environment Weather"),
    CommunicationSymbol(id: "soap", assetName: "soap", displayLabel: "Soap", category: "Body & Health", rawCategory: "Healthcare Grooming items"),
    CommunicationSymbol(id: "soft", assetName: "soft", displayLabel: "Soft", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "some", assetName: "some", displayLabel: "Some", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "son", assetName: "son", displayLabel: "Son", category: "People & Places", rawCategory: "People Relationship"),
    CommunicationSymbol(id: "soup", assetName: "soup", displayLabel: "Soup", category: "Food & Drink", rawCategory: "Food Meals and snacks"),
    CommunicationSymbol(id: "sour", assetName: "sour", displayLabel: "Sour", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "south", assetName: "south", displayLabel: "South", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "spaceship", assetName: "spaceship", displayLabel: "Spaceship", category: "Everyday Objects", rawCategory: "Transport Space"),
    CommunicationSymbol(id: "spain", assetName: "spain", displayLabel: "Spain", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "speak", assetName: "speak", displayLabel: "Speak", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "spicy", assetName: "spicy", displayLabel: "Spicy", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "spotty", assetName: "spotty", displayLabel: "Spotty", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "spring", assetName: "spring", displayLabel: "Spring", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "square", assetName: "square", displayLabel: "Square", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "stable", assetName: "stable", displayLabel: "Stable", category: "Animals & Nature", rawCategory: "Animal Habitat"),
    CommunicationSymbol(id: "star", assetName: "star", displayLabel: "Star", category: "Science & Learning", rawCategory: "Science Astronomy"),
    CommunicationSymbol(id: "starfish", assetName: "starfish", displayLabel: "Starfish", category: "Animals & Nature", rawCategory: "Animal Other Invertebrates"),
    CommunicationSymbol(id: "sticky", assetName: "sticky", displayLabel: "Sticky", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "stock", assetName: "stock", displayLabel: "Stock", category: "Food & Drink", rawCategory: "Food Ingredients"),
    CommunicationSymbol(id: "stool", assetName: "stool", displayLabel: "Stool", category: "People & Places", rawCategory: "Building Furniture"),
    CommunicationSymbol(id: "stop", assetName: "stop", displayLabel: "Stop", category: "Communication", rawCategory: "Communication Signs"),
    CommunicationSymbol(id: "straight", assetName: "straight", displayLabel: "Straight", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "striped", assetName: "striped", displayLabel: "Striped", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "stroke", assetName: "stroke", displayLabel: "Stroke", category: "Animals & Nature", rawCategory: "Animal Activity Grooming"),
    CommunicationSymbol(id: "subsoil", assetName: "subsoil", displayLabel: "Subsoil", category: "Science & Learning", rawCategory: "Science Eco"),
    CommunicationSymbol(id: "sum", assetName: "sum", displayLabel: "Sum", category: "Communication", rawCategory: "Number Activity"),
    CommunicationSymbol(id: "summer", assetName: "summer", displayLabel: "Summer", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "sun", assetName: "sun", displayLabel: "Sun", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "sweden", assetName: "sweden", displayLabel: "Sweden", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "swing", assetName: "swing", displayLabel: "Swing", category: "Everyday Objects", rawCategory: "Leisure Playground"),
    CommunicationSymbol(id: "switzerland", assetName: "switzerland", displayLabel: "Switzerland", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "table", assetName: "table", displayLabel: "Table", category: "People & Places", rawCategory: "Building Furniture"),
    CommunicationSymbol(id: "tall", assetName: "tall", displayLabel: "Tall", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "tap", assetName: "tap", displayLabel: "Tap", category: "Body & Health", rawCategory: "Healthcare Grooming items"),
    CommunicationSymbol(id: "tart", assetName: "tart", displayLabel: "Tart", category: "Food & Drink", rawCategory: "Food Sweets and desserts"),
    CommunicationSymbol(id: "tea", assetName: "tea", displayLabel: "Tea", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "ten", assetName: "ten", displayLabel: "Ten", category: "Communication", rawCategory: "Number"),
    CommunicationSymbol(id: "tennis", assetName: "tennis", displayLabel: "Tennis", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "test", assetName: "test", displayLabel: "Test", category: "Work & School", rawCategory: "Work and School Education"),
    CommunicationSymbol(id: "thanks", assetName: "thanks", displayLabel: "Thanks", category: "Feelings & Descriptions", rawCategory: "People Feelings"),
    CommunicationSymbol(id: "thick", assetName: "thick", displayLabel: "Thick", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "thin", assetName: "thin", displayLabel: "Thin", category: "People & Places", rawCategory: "People Descriptive"),
    CommunicationSymbol(id: "thirsty", assetName: "thirsty", displayLabel: "Thirsty", category: "Food & Drink", rawCategory: "Food Feeding and eating"),
    CommunicationSymbol(id: "through", assetName: "through", displayLabel: "Through", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "tie", assetName: "tie", displayLabel: "Tie", category: "Everyday Objects", rawCategory: "Clothes General"),
    CommunicationSymbol(id: "time", assetName: "time", displayLabel: "Time", category: "Everyday Objects", rawCategory: "Electrical General"),
    CommunicationSymbol(id: "tin", assetName: "tin", displayLabel: "Tin", category: "Food & Drink", rawCategory: "Food Kitchen items"),
    CommunicationSymbol(id: "toad", assetName: "toad", displayLabel: "Toad", category: "Animals & Nature", rawCategory: "Animal Reptiles and Amphibians"),
    CommunicationSymbol(id: "today", assetName: "today", displayLabel: "Today", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "toilet", assetName: "toilet", displayLabel: "Toilet", category: "Body & Health", rawCategory: "Healthcare Grooming items"),
    CommunicationSymbol(id: "toilets", assetName: "toilets", displayLabel: "Toilets", category: "Communication", rawCategory: "Communication Signs"),
    CommunicationSymbol(id: "tomorrow", assetName: "tomorrow", displayLabel: "Tomorrow", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "toothache", assetName: "toothache", displayLabel: "Toothache", category: "Body & Health", rawCategory: "Healthcare Medical conditions"),
    CommunicationSymbol(id: "top", assetName: "top", displayLabel: "Top", category: "Feelings & Descriptions", rawCategory: "Descriptive Position"),
    CommunicationSymbol(id: "topsoil", assetName: "topsoil", displayLabel: "Topsoil", category: "Science & Learning", rawCategory: "Science Eco"),
    CommunicationSymbol(id: "torch", assetName: "torch", displayLabel: "Torch", category: "Everyday Objects", rawCategory: "Electrical General"),
    CommunicationSymbol(id: "tracksuit", assetName: "tracksuit", displayLabel: "Tracksuit", category: "Everyday Objects", rawCategory: "Clothes Sport"),
    CommunicationSymbol(id: "train", assetName: "train", displayLabel: "Train", category: "Everyday Objects", rawCategory: "Transport Rail"),
    CommunicationSymbol(id: "trap", assetName: "trap", displayLabel: "Trap", category: "Animals & Nature", rawCategory: "Animal Activity Misc"),
    CommunicationSymbol(id: "trapezium", assetName: "trapezium", displayLabel: "Trapezium", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "travel", assetName: "travel", displayLabel: "Travel", category: "People & Places", rawCategory: "Holiday and travel"),
    CommunicationSymbol(id: "tuna", assetName: "tuna", displayLabel: "Tuna", category: "Food & Drink", rawCategory: "Food Fish and seafood"),
    CommunicationSymbol(id: "turkey", assetName: "turkey", displayLabel: "Turkey", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "two", assetName: "two", displayLabel: "Two", category: "Communication", rawCategory: "Number"),
    CommunicationSymbol(id: "untie", assetName: "untie", displayLabel: "Untie", category: "Body & Health", rawCategory: "Healthcare Grooming activities"),
    CommunicationSymbol(id: "up", assetName: "up", displayLabel: "Up", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "van", assetName: "van", displayLabel: "Van", category: "Everyday Objects", rawCategory: "Transport Road"),
    CommunicationSymbol(id: "vinegar", assetName: "vinegar", displayLabel: "Vinegar", category: "Food & Drink", rawCategory: "Food Ingredients"),
    CommunicationSymbol(id: "volleyball", assetName: "volleyball", displayLabel: "Volleyball", category: "Everyday Objects", rawCategory: "Sport"),
    CommunicationSymbol(id: "wales", assetName: "wales", displayLabel: "Wales", category: "Countries", rawCategory: "Country Flags"),
    CommunicationSymbol(id: "wall", assetName: "wall", displayLabel: "Wall", category: "People & Places", rawCategory: "Building Structure"),
    CommunicationSymbol(id: "walrus", assetName: "walrus", displayLabel: "Walrus", category: "Animals & Nature", rawCategory: "Animal Fish and Marine mammals"),
    CommunicationSymbol(id: "watch", assetName: "watch", displayLabel: "Watch", category: "Everyday Objects", rawCategory: "Clothes Jewellery"),
    CommunicationSymbol(id: "water", assetName: "water", displayLabel: "Water", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "wavy", assetName: "wavy", displayLabel: "Wavy", category: "Feelings & Descriptions", rawCategory: "Descriptive Shape"),
    CommunicationSymbol(id: "webcam", assetName: "webcam", displayLabel: "Webcam", category: "Everyday Objects", rawCategory: "Electrical Computer"),
    CommunicationSymbol(id: "week", assetName: "week", displayLabel: "Week", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "weekend", assetName: "weekend", displayLabel: "Weekend", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "weigh", assetName: "weigh", displayLabel: "Weigh", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "west", assetName: "west", displayLabel: "West", category: "Feelings & Descriptions", rawCategory: "Descriptive Direction"),
    CommunicationSymbol(id: "wet", assetName: "wet", displayLabel: "Wet", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "what", assetName: "what", displayLabel: "What", category: "Feelings & Descriptions", rawCategory: "Question"),
    CommunicationSymbol(id: "whiteboard", assetName: "whiteboard", displayLabel: "Whiteboard", category: "People & Places", rawCategory: "Building Equipment and devices"),
    CommunicationSymbol(id: "who", assetName: "who", displayLabel: "Who", category: "Feelings & Descriptions", rawCategory: "Question"),
    CommunicationSymbol(id: "whole", assetName: "whole", displayLabel: "Whole", category: "Feelings & Descriptions", rawCategory: "Descriptive Quantity"),
    CommunicationSymbol(id: "why", assetName: "why", displayLabel: "Why", category: "Feelings & Descriptions", rawCategory: "Question"),
    CommunicationSymbol(id: "wife", assetName: "wife", displayLabel: "Wife", category: "People & Places", rawCategory: "People Relationship"),
    CommunicationSymbol(id: "wii", assetName: "wii", displayLabel: "Wii", category: "Everyday Objects", rawCategory: "Electrical Media"),
    CommunicationSymbol(id: "wine", assetName: "wine", displayLabel: "Wine", category: "Food & Drink", rawCategory: "Drink Type"),
    CommunicationSymbol(id: "winter", assetName: "winter", displayLabel: "Winter", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "wishbone", assetName: "wishbone", displayLabel: "Wishbone", category: "Food & Drink", rawCategory: "Food Poultry"),
    CommunicationSymbol(id: "work", assetName: "work", displayLabel: "Work", category: "Everyday Objects", rawCategory: "Tools Actions"),
    CommunicationSymbol(id: "worksheet", assetName: "worksheet", displayLabel: "Worksheet", category: "Work & School", rawCategory: "Work and School Education"),
    CommunicationSymbol(id: "wrap", assetName: "wrap", displayLabel: "Wrap", category: "Celebrations", rawCategory: "Celebration Event"),
    CommunicationSymbol(id: "xray", assetName: "xray", displayLabel: "Xray", category: "Body & Health", rawCategory: "Healthcare Medical items"),
    CommunicationSymbol(id: "yes", assetName: "yes", displayLabel: "Yes", category: "Feelings & Descriptions", rawCategory: "Descriptive State"),
    CommunicationSymbol(id: "yesterday", assetName: "yesterday", displayLabel: "Yesterday", category: "Feelings & Descriptions", rawCategory: "Descriptive Time"),
    CommunicationSymbol(id: "yogurt", assetName: "yogurt", displayLabel: "Yogurt", category: "Food & Drink", rawCategory: "Food Dairy"),
    CommunicationSymbol(id: "zip", assetName: "zip", displayLabel: "Zip", category: "Everyday Objects", rawCategory: "Clothes Accessories"),
    ]

}
